# Site settings
title: veronica | codes
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "https://veronicacannon.github.io/"
author:
  name: "Veronica Cannon"
  email: "me@veronicacannon.com"
  url: "https://veronica.codes"

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
